---

- name: Copy the epel packages 
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx_ansible.repo
  when: ansible_os_family == "RedHat"

- name: Install the nginx packages 
  yum: name={{ item }} state=present
  with_items: redhat_pkg
  when: ansible_os_family == "RedHat"

- name: Install the nginx packages 
  apt: name={{ item }} state=present update_cache=yes
  with_items: ubuntu_pkg
  environment: env
  when: ansible_os_family == "Debian"

- name: start the nginx service
  service: name=nginx state=started enabled=yes

