- include: install.yml
  when: skip_install is not defined or skip_install != "true"

- include: config.yml
  when: skip_config is not defined or skip_config != "true"

#- name: "installing"
  #debug: msg=installing
  #when: skip_install is not defined or skip_install != "true"

#- name: "config"
  #debug: msg=configging
  #when: skip_config is not defined or skip_config != "true"
#- name: "testing"
  #debug: msg="{{skip_config}}"
